# Generated by Django 4.2.2 on 2023-09-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscrip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sinsevi',
            table='sinsevi',
        ),
    ]
