# Generated by Django 4.2.2 on 2023-09-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscrip', '0002_alter_sinsevi_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estud_nacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_estud', models.BigIntegerField(blank=True, null=True)),
                ('cve_nacion', models.IntegerField()),
                ('cve_campus', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'estud_nacion',
                'managed': False,
            },
        ),
    ]
